name: persian_datetime_picker
description: A persian (farsi,shamsi) datetime picker for flutter, inspired by material datetime picker.
version: 2.4.0
homepage: https://github.com/arfoon/afghani-datetime-picker

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
