name: afghani_datetime_picker
description: A afghani (dari, hijri) datetime picker for flutter, inspired by material datetime picker.
version: 1.0.0
homepage: https://github.com/iampopal/afghani-datetime-picker

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
